name: Futurebuilt
favicon: null
layout_spectrum: 0.2526601057033986
typography_spectrum: 0.3900989687535912
title: Imagine your digital future. Together.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-53438969-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4092022990807891
  lightness: 0.8922064718790352
  saturation: 0.418273126706481
  rhythmicContrast: 0.44922430790029466
purpose: []
